print("BIENVENIDOS A HISTORIAS LOCAS")
print("Hoy les traemos:QUERIDO PAPÁ NOEL")
print("INSTRUCCIONES DEL JUEGO:")
print("1-Completa el cuadro con lo primero que se le ocurra en cada indicación")
print("""2-COSAS A TENER EN CUENTA:
Un sustantivo es: Palabra que sirve para designar los seres vivos o las cosas materiales o mentales.
Un adjetivo es: Clase de palabra que acompaña al sustantivo para expresar una cualidad de la cosa designada por él o para determinar o limitar la extensión del mismo.
Un verbo: Expresa una acción, movimiento, existencia, consecución, condición o estado del sujeto.
""")
print("3-Lee como ha quedado la historia y ha reirse mucho")
sustantivo = input("Ingresa un sustantivo: ")
adjetivo = input("Ingresa un adjetivo: ")
miembro_de_la_familia = input("Ingresa un miembro de la familia: ")
verbo = input("Ingresa un verbo: ")
sustantivo2 = input("Ingresa un sustantivo: ")
personaje_famoso = input("Ingresa un personaje famoso: ")
verbo2 =  input("Ingresa un verbo: ")
animal_mascota = input("Ingresa un animal/mascota: ")
lugar = input("Ingresa un lugar: ")
sustantivo3 = input("Ingresa un sustantivo: ")
sustantivo4 = input("Ingresa un sustantivo: ")
adjetivo = input("Ingresa un adjetivo: ")
sustantivo5 = input("Ingresa un sustantivo: ")
sustantivo6 = input("Ingresa un sustantivo: ")
adjetivo2 = input("Ingresa un adjetivo: ")
lugar2 = input("Ingresa un lugar: ")
sustantivo7 = input("Ingresa un sustantivo: ")
nombre_de_persona = input("Ingresa un nombre de persona: ")
adjetivo3 = input("Ingresa un adjetivo: ")

print(f"Querido Papá Noel, Soy un/a {sustantivo} muy {adjetivo}.")
print(f"Siempre ayudo a mi {miembro_de_la_familia} en casa.")
print(f"Todos los días tengo que {verbo} con el/la {sustantivo2}. ")
print(f"Una vez por semana ayudo a {personaje_famoso} a {verbo2} su {animal_mascota} cuando va a trabajar a {lugar}.")
print(f" Esta es mi lista de {sustantivo3}. ")
print(f"Quiero un/a {sustantivo4} ,{adjetivo}.")
print(f"Si me traes un/a {sustantivo5} voy a ser el/la {sustantivo6} más {adjetivo2} del /la {lugar2}. ")
print(f"También si le puedes dar un/a {sustantivo7} a {nombre_de_persona} voy a estar muy {adjetivo3} ¡Feliz Navidad! ")

